// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC3Kg50AIxLkLFkMACVII0V65u3ESBa3I',
    appId: '1:46812338631:web:8b61d40c96204a23c161e2',
    messagingSenderId: '46812338631',
    projectId: 'food-delivery-2fab4',
    authDomain: 'food-delivery-2fab4.firebaseapp.com',
    storageBucket: 'food-delivery-2fab4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIe99nPxHkgd1k_Ac8zWjKwo-YRkP2foM',
    appId: '1:46812338631:android:28f0890ee724579bc161e2',
    messagingSenderId: '46812338631',
    projectId: 'food-delivery-2fab4',
    storageBucket: 'food-delivery-2fab4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCzA0E7h5O3DHtc0Q8_FhndiASsA3xFEA',
    appId: '1:46812338631:ios:6da665086e91bde5c161e2',
    messagingSenderId: '46812338631',
    projectId: 'food-delivery-2fab4',
    storageBucket: 'food-delivery-2fab4.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCzA0E7h5O3DHtc0Q8_FhndiASsA3xFEA',
    appId: '1:46812338631:ios:6da665086e91bde5c161e2',
    messagingSenderId: '46812338631',
    projectId: 'food-delivery-2fab4',
    storageBucket: 'food-delivery-2fab4.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC3Kg50AIxLkLFkMACVII0V65u3ESBa3I',
    appId: '1:46812338631:web:eb2ab806ad128291c161e2',
    messagingSenderId: '46812338631',
    projectId: 'food-delivery-2fab4',
    authDomain: 'food-delivery-2fab4.firebaseapp.com',
    storageBucket: 'food-delivery-2fab4.appspot.com',
  );
}
